= myDoc
Aloyse Gilbert <aloyse.gilbert@chdn.lu>
v0.2, 16-08-2015
:icons: font
:toc: left
:toclevels: 2
:pdf-page-size: A4
:source-highlighter: highlightjs

documenting, the ascii way.


== Rules

some text icon:heart[size=2x]
[sidebar]
.Related information
--
This is aside text.

It is used to present information related to the main content.
--

[source,ruby]
.app.rb
----
require 'sinatra'
get '/hi' do
  "Hello World!"
end
----

[source,xml]
<meta name="viewport"
  content="width=device-width, initial-scale=1.0">

This is normal content.


follow the rules as best-practices, update this section, and ...

TIP: *re-evaluate* the rules as often as you can

--
[horizontal]
APPLY::	stick to the rules
KISS::	Keep It Small and Simple
SECTIONS::
	* use initial capital
--

== Toolchain
The tools used, and how to work with them

Linux::
* TODO

Windows::
* Notepad++ with https://github.com/edusantana/asciidoc-highlight[syntaxHighlighter^]
* preview in browsers using http://asciidoctor.org/docs/editing-asciidoc-with-live-preview/[Addons^]
* http://jruby.org/download[JRuby^] install
+
[source]
gem install asciidoctor
gem install --pre asciidoctor-pdf


== Generate documents

=== Html5

generate html5 with external css (to modify it :)

`asciidoctor -a linkcss .\README.adoc` will give a html5 document named link:README.html[`README.html`^]
   
use the `-b xhtml5` argument to produce xml compliant html5  
   
=== Pdf

`asciidoctor-pdf .\README.adoc` will give a pdf document named link:README.pdf[`README.pdf`^]

== Style

get stylish ...
TODO

== Issues

* asciidoctor-pdf indents Admonitions too far - compared to html5

IMPORTANT: too far to the right...

* firefox plugin is not complete.

* pdf fonts are limited eg. `UTF-8 snowman` -> [☃] will not be rendered


	